version: 2.1

jobs:

  say-hello:
   
    docker:
      - image: cimg/base:stable 
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  Print_hello:
    docker:
      -image: cimg/base:stable
    steps:
      - run: 
          name: "print hello"          
          command: "echo hello to the world"
  print_world:
    docker:
      -image: cimg/base:stable
    steps:
      - run:
          name: "print_world"
          command: "echo world"          

workflows:
  say-hello-workflow:
    jobs:
      - say-hello

  my-job-workflow:
    jobs:    
      - print_hello
      - print_world:
          requires:
            - print_hello