version: 2.1

jobs:
  kelvin-sample:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Print out Kelvin's name and say hello j
          command: |
            echo "Hello Kelvin, Big boss!" >> name.txt
            cat name.txt  
        
  smart-process:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run: 
          name: Tell Mr Kelvin that this process is working
          command: |
            mkdir kelvin
            cd kelvin
            echo https://sagencoders.com >> ayorinde.txt
            echo https://google.com >> ayorinde.txt
            echo https://udacity.com >> ayorinde.tx
            tail -2 ayorinde.txt

  dull-process:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run: 
          name: The doll process
          command: |
            echo "I am a dull process"
      - run: 
          name:  Another dull process
          command: echo "I told you before, I am a dull process!"


workflows:
  kelvin:
    jobs:
      - kelvin-sample
      - smart-process
      - dull-process:
          requires: [kelvin-sample, smart-process]